import React from 'react';
import { SEO } from '../components/SEO';

export default function Disclaimer() {
  return (
    <div className="p-4 sm:p-8 w-full max-w-4xl mx-auto flex-grow flex flex-col mt-4 mb-16">
      <SEO 
        title="Disclaimer | Rural Utility Cost" 
        description="Legal disclaimer regarding the estimates and calculations provided by Rural Utility Cost." 
      />
      
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-8 sm:p-12">
        <h1 className="text-3xl font-black text-gray-900 dark:text-white mb-2 tracking-tight">Disclaimer</h1>
        <p className="text-sm text-gray-500 mb-8 border-b border-gray-100 dark:border-gray-700 pb-4">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">Estimates Only</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed font-medium">
              All calculator results provided on RuralUtilityCost.com are estimates and should be used strictly as a baseline guide.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">Variable Factors</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              Real-world pricing, availability, flow rates, capacities, and contractor fees are highly regional and subject to constant market fluctuations. Unseen factors such as local geology, supply chain issues, inflation, and specific ordinances can drastically impact the final cost of any rural utility project.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">No Professional Relationship</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              Using our calculators does not establish any professional-client relationship. The information on this site is not a substitute for formal bids or inspections from licensed professionals, engineers, or local health departments.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">No Liability</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              We are not responsible or liable for any project overruns, losses, property damages, or legal issues resulting from reliance on the figures generated by this website. Always get standard localized bids before proceeding with construction or land development.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
