import React from 'react';
import { SEO } from '../components/SEO';

export default function TermsOfUse() {
  return (
    <div className="p-4 sm:p-8 w-full max-w-4xl mx-auto flex-grow flex flex-col mt-4 mb-16">
      <SEO 
        title="Terms of Use | Rural Utility Cost" 
        description="Terms of Use for Rural Utility Cost. Read our terms regarding the use of our calculators and website." 
      />
      
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-8 sm:p-12">
        <h1 className="text-3xl font-black text-gray-900 dark:text-white mb-2 tracking-tight">Terms of Use</h1>
        <p className="text-sm text-gray-500 mb-8 border-b border-gray-100 dark:border-gray-700 pb-4">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">1. Acceptance of Terms</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              By accessing and using RuralUtilityCost.com (the "Site"), you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">2. Informational Purposes Only</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              All content provided on this Site, including all calculator results and estimates, is for informational purposes only. The estimates generated by our tools are based on broad industry averages and user-provided inputs. They do not constitute professional advice, absolute quotes, or guarantees of pricing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">3. User Responsibility</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              You are entirely responsible for independent verification of any results generated by this Site. We strongly advise consulting with licensed professionals, local utility providers, contractors, or government agencies before making any financial or structural decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">4. Limitation of Liability</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              In no event shall RuralUtilityCost.com or its owners be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with your access or use of or inability to access or use the Site or any reliance on calculator outputs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">5. Intellectual Property</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              The tools, design, and original text on this website are the intellectual property of RuralUtilityCost.com. You may not scrape, copy, or redistribute the calculators or logic without written permission.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
